<html>
<head>
</head>
<body>
 <h1>Hola soy un titulo</h1>
 <?php
 // INICIA CODIGO php
 //Esto es un comentario
 /* todo lo que este aqui dentro
 se considera un comentario
 */
 // COMANDO ECHO DEVUELVE UN VALOR
 echo "HOLA SOY UN PARRAFO";
 echo "<br>";  //salto de linea
 echo 3+3;  /*realiza operaciones
              que no se puede en html.*/
 // TERMINA php
 ?>

<?php
// definimos una variable con un texto
$miVariable = "Hola variable";
// visualizamos la variable en el explorador 
echo $miVariable;
//otro ejemplo variable miValor igual a 2
echo "<br>";
$miValor = 2;
//visualizamos sin embargo realizamos una multiplicacion * 3
echo 3*$miValor;

?>
 </BODY>
 </html>